### ISSUE TITLE
Screenshots ?

### ISSUE THREAD

**Issue by cleme29** [tomcdj71/ruTorrent-MaterialDesign#1]
Hi man !
Screenshots would be welcome !
Thanks,

**Comment by tomcdj71** [comment]
Hey, sorry for that, it's my 1st time.

![material design 1](https://cloud.githubusercontent.com/assets/15751462/14882492/6557d300-0d39-11e6-82fb-5b600ada87a9.png)

![material design 2](https://cloud.githubusercontent.com/assets/15751462/14882542/9f0c4c70-0d39-11e6-81fb-b412a41e6c01.png)
