### ISSUE TITLE
Possible to ad Ratiocolor plugin support?

### ISSUE THREAD

**Issue by TheBreznsoiza** [tomcdj71/ruTorrent-MaterialDesign#2]
Possible to ad Ratiocolor plugin support?

[RatioColor](https://github.com/Gyran/rutorrent-ratiocolor)

Thanks

**Comment by Spyneur** [comment]
Hello @DasBlatz 

Try this tweak to add Ratiocolor support : 

In file 

> ~/rutorrent/plugins/theme/themes/MaterialDesign/style.css

Replace line 182

`background:#252525!important` 

By

`background:!important`

Ratiocolor should work again.

![ratiocolormaterialdesign](https://cloud.githubusercontent.com/assets/15103741/17689233/63fc2c7e-6386-11e6-8f7b-2a3069752494.PNG)

If you don't want to change style.css of MaterialDesign theme, you can try this : 

In file

> ~/rutorrent/plugins/ratiocolor/init.js

Replace line 38

`changeWhat = "cell-background";`

By

`changeWhat = "font";`

![ratiocolor_font](https://cloud.githubusercontent.com/assets/15103741/17689489/55ef558c-6388-11e6-843f-a20ff24d690d.PNG)

(Sorry for my poor english, i'm french guy ^^)

**Comment by TheBreznsoiza** [comment]
Thanks for the reply, I use the second solution now with the font. 
looks quite better than the background thing on your Theme. 
btw your Theme is awesome, best one for rutorrent I've found

**Comment by Spyneur** [comment]
Oh no, it's not my theme, i'm a simple user, like you ^^
I'm glad to help you :p
